"""Add archived column to Commande

Revision ID: 5c71366aec58
Revises: 
Create Date: 2024-11-03 16:12:47.177998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c71366aec58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commande', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
